# Generated by Django 5.1.5 on 2026-09-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size', models.CharField(max_length=100)),
                ('img', models.URLField(max_length=500)),
                ('accent', models.CharField(max_length=200)),
                ('notes', models.JSONField(default=list)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
