# Generated by Django 5.1.5 on 2026-09-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('floral', 'Floral'), ('woody', 'Woody'), ('oriental', 'Oriental'), ('fresh', 'Fresh')], default='floral', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
